S02 connection
WildCodeSchool-2024-02/PHP-REM-POEC-05-CuirCuirMoustache pull request #10
Opened 2024-07-23 15:20 UTC by Maurice-Mbilia

2024-07-24 15:56 UTC, Maurice-Mbilia commented
Salut les gens, 
je ne n'arrive pas à passer le phpmd :
Running task 1/4: phpcs... ✔
Running task 2/4: phpstan... ✔
Running task 3/4: phpmd... ✘
Running task 4/4: phpunit... ✔ 
Et pour contourner ce fait, j'ai fait le commit comme suit : 
$ git commit -m "gestion de compte et edit compte" -n

2024-07-24 17:28 UTC, GuillaumeCregut commented
Alors :
1/ Conflits sur gitignore
src/View/Admin/User/index.html.twig
src/routes.php

2/ pas de by pass du controle de commit avec le -n, sinon la CI plante.
Donc, voir quel message est donné par phpMD et le résoudre

2024-07-24 19:50 UTC, Maurice-Mbilia commented
Conflits résolus

2024-07-25 06:49 UTC, GuillaumeCregut commented
What did you test ?
Commits are not clear

2024-07-29 06:20 UTC, GuillaumeCregut commented on src/Controller/Auth/AuthController.php
>      }
PHP possède un algo performant pour encoder les mots de passe.
Autant l'utiliser, 
Tu as au choix BCrypt et Argon2I, qui sont reconnu comme leader .
SHA n'est absolument pas performant et sécure pour ce genre de chose, merci de NE PAS l'UTILISER

2024-07-29 06:28 UTC, Maurice-Mbilia commented
Bonjour Guillaume,
Au fait, j'avais proposé l'algorithme BCrypt, mais le groupe avait préféré
de faire cette méthode. C'est pour cela. Si tel est le cas, nous disposons
déjà d'une version qui marche super bien 👍

Le lun. 29 juil. 2024 à 08:20, Guillaume Crégut ***@***.***>
a écrit :

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/Controller/Auth/AuthController.php
> <https://github.com/WildCodeSchool-2024-02/PHP-REM-POEC-05-CuirCuirMoustache/pull/10#discussion_r1694636404>
> :
>
> > @@ -215,9 +209,20 @@ private function validationForm(array $userData): array
>          if (empty($userData['password'])) {
>              $errors[] = 'Le mot de passe est requis';
>          }
> -        if (empty($userData['phone'])) {
> -            $errors[] = 'Le téléphone est requis';
> +        if (empty($userData['phone']) || !preg_match('/^[0-9]{10}$/', $userData['phone'])) {
> +            $errors[] = 'Le numéro de téléphone est requis et doit être valide.';
>          }
>          return $errors;
>      }
>
> PHP possède un algo performant pour encoder les mots de passe.
> Autant l'utiliser,
> Tu as au choix BCrypt et Argon2I, qui sont reconnu comme leader .
> SHA n'est absolument pas performant et sécure pour ce genre de chose,
> merci de NE PAS l'UTILISER
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WildCodeSchool-2024-02/PHP-REM-POEC-05-CuirCuirMoustache/pull/10#pullrequestreview-2204019911>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMCLVJWM6YWTQAKR6OND7Y3ZOXNMTAVCNFSM6AAAAABLKVH5NKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMBUGAYTSOJRGE>
> .
> You are receiving this because you authored the thread.Message ID:
> <WildCodeSchool-2024-02/PHP-REM-POEC-05-CuirCuirMoustache/pull/10/review/2204019911
> @github.com>
>

2024-07-29 06:35 UTC, GuillaumeCregut commented
PHP fournit une fonction simple a utiliser et performante :password_hash($mdp, $algo);
$algo,  par défaut est BCrypt avec une complexité de 10 (12 dans la version 8.4).  On peut préférer PASSWORD_ARGON2I
Et pour vérifier le mot de passe : password_verify($mpd,$dbMdp);

Un peu de lecture sur la sécurité :
https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html

2024-08-01 07:36 UTC, GuillaumeCregut requested changes

2024-08-01 07:36 UTC, GuillaumeCregut commented on .gitignore
> +<<<<<<< HEAD
Il reste des traces de conflit dans gitignore

2024-08-01 07:36 UTC, GuillaumeCregut commented on src/Controller/Auth/AuthController.php
> +        session_destroy();
Juste destroy, pas besoin de unset

2024-08-01 12:00 UTC, Maurice-Mbilia commented
Rebonjour Guillaume,
C'est bon pour moi, j'ai résolu les conflits

Le jeu. 1 août 2024 à 09:36, Guillaume Crégut ***@***.***> a
écrit :

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In .gitignore
> <https://github.com/WildCodeSchool-2024-02/PHP-REM-POEC-05-CuirCuirMoustache/pull/10#discussion_r1699577716>
> :
>
> > @@ -1,3 +1,13 @@
> +<<<<<<< HEAD
>
> Il reste des traces de conflit dans gitignore
> ------------------------------
>
> In src/Controller/Auth/AuthController.php
> <https://github.com/WildCodeSchool-2024-02/PHP-REM-POEC-05-CuirCuirMoustache/pull/10#discussion_r1699581691>
> :
>
> > +
> +        try {
> +            echo $this->twig->render($template, $params);
> +        } catch (LoaderError | RuntimeError | SyntaxError $e) {
> +            echo "Erreur de rendu de template : " . $e->getMessage();
> +        }
> +    }
> +
> +    public function authLogout()
> +    {
> +        if (session_status() === PHP_SESSION_NONE) {
> +            session_start();
> +        }
> +        // Détruire la session
> +        session_unset();
> +        session_destroy();
>
> Juste destroy, pas besoin de unset
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WildCodeSchool-2024-02/PHP-REM-POEC-05-CuirCuirMoustache/pull/10#pullrequestreview-2211864338>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMCLVJVTUOM2XI52CHJNKLTZPHQRPAVCNFSM6AAAAABLKVH5NKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMJRHA3DIMZTHA>
> .
> You are receiving this because you authored the thread.Message ID:
> <WildCodeSchool-2024-02/PHP-REM-POEC-05-CuirCuirMoustache/pull/10/review/2211864338
> @github.com>
>

2024-08-02 07:57 UTC, closed without merging